### ISSUE TITLE
How to test the model trained on FEMNIST dataset if the users in the testing set are disjoint from the uesers in the training set?

### ISSUE THREAD

**Issue by Wuyxin** [henrikmarklund/arm#4]
Hi,

I got one problem when i running your code on FEMNIST dataset.

I noted that you labeled the group ids of instances from their user ids. However, as descirbed in your paper, the users in the testing set are disjoint from the users in the training set. Thus, when evaluating the trained model, 
```
python test_on_groups.py --eval_on test --use_context 1 --binning 1  --ckpt_folders CKPT --n_test_dists 15
```
 I got the following error report

```
Traceback (most recent call last):
  File "test.py", line 261, in <module>
    test_stats = test(args, eval_on='test')
  File "test.py", line 136, in test
    test_loader, eval_dists, split='test')
  File "/home/wuyx/FL-baseline/utils/eval_utils.py", line 215, in evaluate_mixtures
    accuracies_corners = eval_dists_fn(split, args, model, loader, corner_dists, n_samples_per_dist=n_samples_per_dist)
  File "/home/wuyx/FL-baseline/utils/eval_utils.py", line 144, in eval_dists_fn
    preds_all, labels_all = eval_dist(dist, model, loader, args, n_samples_per_dist)
  File "/home/wuyx/FL-baseline/utils/eval_utils.py", line 114, in eval_dist
    loader.sampler.set_sub_dist(dist)
  File "/home/wuyx/FL-baseline/datasets/utils/samplers.py", line 258, in set_sub_dist
    self.weights = torch.as_tensor(self._get_dist(dist), dtype=torch.double)
  File "/home/wuyx/FL-baseline/datasets/utils/samplers.py", line 275, in _get_dist
    p_over_examples = np.sum(self.group_ids_probs_pre * p_over_groups, axis=1)
ValueError: operands could not be broadcast together with shapes (13328,167) (741,)
```
where 741 is the number of users in the training set, 13328 and 167 are the number of instances and the number of users in the testing set respectively. I think that's because computing the distribution shift needs special operations when test groups are not sampled identically to the training groups, but i don't understand how to deal with it and i can't find this evaluation process in your repo either.

Looking foward to your answer~

**Comment by Wuyxin** [comment]
i realize where's the problem now... i accidentally set binning=True. It works fine after i set binning=False.
